# Disable host verification.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          args:
            - -linkerd-metrics-api-addr=metrics-api.linkerd.svc.cluster.local:8085
            - -cluster-domain=cluster.local
            - -controller-namespace=linkerd
            - -log-level=info
            - -log-format=plain
            - -enforced-host=^(localhost|127\.0\.0\.1|web\.linkerd\.svc\.cluster\.local|web\.linkerd\.svc|\[::1\]|192.168.56.\d{1,3})(:\d+)?$
            - -enable-pprof=false
