# -*- mode: ruby -*-
# vi: set ft=ruby :

private_key_path = ENV["private_key_path"]
virtual_machine_image = ENV["virtual_machine_image"]
virtual_machine_index = ENV["virtual_machine_index"]
virtual_machine_hostname = ENV["virtual_machine_hostname"]
virtual_machine_ip = ENV["virtual_machine_ip"]

Vagrant.configure("2") do |config|
  config.vm.define "#{virtual_machine_image}-#{virtual_machine_index}" do |config|
    config.vm.box = virtual_machine_image
    config.vm.box_url = "file://../packer-vmis/#{virtual_machine_image}.box"
    config.vm.network "private_network", ip: virtual_machine_ip
    config.vm.hostname = virtual_machine_hostname
  
    config.vm.provider "virtualbox" do |config_vm|
      config_vm.gui = false
      config_vm.name = "#{virtual_machine_image}-#{virtual_machine_index}"
      config_vm.cpus = 4
      config_vm.memory = 8192
  
      config.ssh.connect_timeout = 20
      config.ssh.username = "vagrant"
      config.ssh.insert_key = false
      config.ssh.private_key_path = private_key_path
    end
  end
end