# -*- mode: ruby -*-
# vi: set ft=ruby :

virtual_machine_image = ENV["virtual_machine_image"] #|| "ubuntu-20.04.3-live-server-amd64"
private_key_path = ENV["private_key_path"] #|| "/home/slav/.ssh/virtual_id_ed25519"
virtual_machine_index = ENV["virtual_machine_index"]

Vagrant.configure("2") do |config|
  config.vm.define "#{virtual_machine_image}-#{virtual_machine_index}" do |config|
    config.vm.box = virtual_machine_image
    config.vm.box_url = "file://../#{virtual_machine_image}.box"
  
    config.vm.provider "virtualbox" do |config_vm|
      config_vm.gui = false
      config_vm.name = "#{virtual_machine_image}-#{virtual_machine_index}"
      config_vm.cpus = 4
      config_vm.memory = 8192
  
      config.ssh.connect_timeout = 20
      config.ssh.username = "vagrant"
      config.ssh.insert_key = false
      config.ssh.private_key_path = private_key_path
    end
  end
end