global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      name: additional-scrape-configs
      key: prometheus-additional-scrape-configs.yaml
