network:
  version: 2
  renderer: NetworkManager
  ethernets:
    ens33:
      dhcp4: no
      addresses: ["{{ k8s_master_pod_network_cidr }}"]
      gateway4: "{{ k8s_node_public_ip }}"
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
