private_key_path = ENV["private_key_path"]
virtual_machine_image = ENV["virtual_machine_image"]
virtual_machine_index = ENV["virtual_machine_index"]
ip_base = ENV["ip_base"]
ip_offset = ENV["ip_offset"].to_i
#count_index = ENV["count_index"].to_i

cluster_name = ENV["cluster_name"]

node_name = ENV["node_name"]
node_cpus = ENV["node_cpus"].to_i
node_memory = ENV["node_memory"].to_i
node_count = ENV["node_count"].to_i

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.ssh.private_key_path = private_key_path

    (1..node_count).each do |i|
        config.vm.define "#{node_name}-#{i}" do |node|
            node.vm.box = virtual_machine_image
            node.vm.box_url = "file://../packer-vmis/#{virtual_machine_image}.box"
            node.vm.network "private_network", ip: "#{ip_base}.#{i + ip_offset}"
            node.vm.hostname = "#{node_name}-#{i}"
            node.vm.provider "virtualbox" do |v|
                v.memory = node_memory
                v.cpus = node_cpus
            end            
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "./roles/k8s.yml"
                #Redefine defaults
                ansible.extra_vars = {
                    k8s_cluster_name: cluster_name,   
                    # The below are repeated because of Ansible configuration, consider refactoring                 
                    k8s_master_admin_user:  "vagrant",
                    k8s_master_admin_group: "sudo",
                    k8s_node_admin_user:  "vagrant",
                    k8s_node_admin_group: "sudo",
                    k8s_master_apiserver_advertise_address: "#{ip_base}.#{i + ip_offset}",
                    k8s_master_node_name: "#{node_name}-#{i}",
                    k8s_node_public_ip: "#{ip_base}.#{i + ip_offset}"
                }                
            end
        end
    end
end
