private_key_path = ENV.fetch("private_key_path", "/home/slav/.ssh/virtual_id_ed25519")
virtual_machine_image = ENV.fetch("virtual_machine_image", "ubuntu-22.10-live-server-amd64")
# virtual_machine_index = ENV.fetch("virtual_machine_index", "")
ip_base = ENV.fetch("ip_base", "192.168.56")
ip_offset = ENV.fetch("ip_offset", "11").to_i
#count_index = ENV.fetch("count_index", "").to_i

cluster_name = ENV.fetch("cluster_name", "kubernetes-cluster")

node_name = ENV.fetch("node_name", "worker")
node_cpus = ENV.fetch("node_cpus", "1").to_i
node_memory = ENV.fetch("node_memory", "1024").to_i
node_count = ENV.fetch("node_count", "2").to_i

VAGRANT_EXPERIMENTAL="disks"
VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|
    # config.vm.network "public_network"

    config.ssh.insert_key = false
    config.ssh.private_key_path = private_key_path

    # It seems `vagrant` cannot work with cyrillic characters; 
    # ssee https://github.com/hashicorp/vagrant/issues/13033
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "/home/slav/.vagrant.tmp", "/vagrant", disabled: false

    (1..node_count).each do |i|
        config.vm.define "#{node_name}-#{i}" do |node|
            node.vm.box = virtual_machine_image
            node.vm.box_url = "file://../packer-vmis/#{virtual_machine_image}.box"
            node.vm.network "private_network", ip: "#{ip_base}.#{i + ip_offset}"
            node.vm.hostname = "#{node_name}-#{i}"
            node.vm.provider "virtualbox" do |v|
                v.memory = node_memory
                v.cpus = node_cpus
            end
            node.vm.disk :disk, size: "40GB", primary: true      
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "./roles/k8s.yml"
                #Redefine defaults
                ansible.extra_vars = {
                    k8s_cluster_name: cluster_name,   
                    # The below are repeated because of Ansible configuration, consider refactoring                 
                    k8s_master_admin_user:  "vagrant",
                    k8s_master_admin_group: "sudo",
                    k8s_node_admin_user:  "vagrant",
                    k8s_node_admin_group: "sudo",
                    k8s_master_apiserver_advertise_address: "#{ip_base}.#{i + ip_offset}",
                    k8s_master_node_name: "#{node_name}-#{i}",
                    k8s_node_public_ip: "#{ip_base}.#{i + ip_offset}"
                }                
            end
        end
    end
end
