apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-grafana-lb
  namespace: argocd-system
spec:
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
